# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Application-Plugin-BREAD
version:      0.11_1
version_from: lib/CGI/Application/Plugin/BREAD.pm
installdirs:  site
requires:
    CGI::Application:              4
    Class::DBI:                    0
    Class::DBI::FormBuilder:       0
    HTML::FillInForm:              1
    HTML::Pager:                   0.03
    HTML::Template:                1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
